#!/bin/bash

do_icecream=1
do_cross_static=0
do_cross_shared=1
do_optional_compiler_languages=0
rm -f libgcj*.spec libgcj*.changes libffi*.spec libffi*.changes gcc*.spec cross*.spec cross*.changes

# Default is to generate the normal gcc package
# unless a parameter is given.  In case that it is '-*',
# that parameter will be used as suffix for the package name
# and as suffix for the install path (/opt/gccSUFFIX)
# In case that it is '[0-9]*', that parameter will be used
# as a suffix for a versioned package name.

if [ $# -lt 1 ]; then
	outfile=gcc.spec
else
	case $1 in
	[0-9]*)
	  base_ver=$1
	  outfile=gcc$1.spec
	;;
	*)
	  exit 1
	;;
	esac
fi

	: > $outfile
	if test "$do_optional_compiler_languages" = "1"; then
	    echo '%define run_tests 1' >> $outfile
	    echo '%define build_optional_compiler_languages 1' >> $outfile
	fi
	sed -e 's%@base_ver@%'$base_ver'%g' \
	    gcc.spec.in \
	| sed -n -e '{
/^# PACKAGE-BEGIN/h
/^# PACKAGE-BEGIN/,/^# PACKAGE-END/H
/^# PACKAGE-BEGIN/,/^# PACKAGE-END/!p
/^# PACKAGE-END/{g
s/@variant@//g
p
g
s/@variant@/-32bit/g
p
g
s/@variant@/-64bit/g
p
}
}' >> $outfile

add_cross() {
  local pkgname="$1"; shift
  local rpmtarget="$1"; shift
  local triplet="$1"; shift

  # Prepare personal cross.spec.in
  outfile=$pkgname.spec cross_arch=$triplet /bin/bash ./cross.spec.sh > cross.spec.in

  exclarch=`echo $rpmtarget | sed -e 's/ppc$/ppc64/'`
  echo "%define pkgname $pkgname" > $pkgname.spec
  echo "%define cross_arch $rpmtarget" >> $pkgname.spec
  echo "%define gcc_target_arch $triplet" >> $pkgname.spec
  echo "$@" >> $pkgname.spec
  { sed -n -e '1,/COMMON-BEGIN/p' cross.spec.in
    sed -n -e '/COMMON-BEGIN/,/COMMON-END/p' $outfile
    sed -n -e '/COMMON-END/,$p' cross.spec.in; } |
    sed -e "s#@base_ver@#$base_ver#" \
	-e "s/^\(ExclusiveArch.*\) $exclarch /\1 /" \
      >> $pkgname.spec
  test -f gcc$base_ver.changes && ln -f gcc$base_ver.changes $pkgname.changes
  rm cross.spec.in
}

# We now support "proper" cross-compilers to suse targets via a
# cross-glibc package, enable that via for example
#
# add_cross cross-aarch64-gcc$base_ver aarch64 aarch64-tizen-linux
#
# For now keep the old way of doing things
if test "$do_icecream" = 1 ; then
add_cross cross-aarch64-gcc$base_ver aarch64 aarch64-tizen-linux %define gcc_icecream 1
add_cross cross-armv7l-gcc$base_ver armv7l armv7l-tizen-linux-gnueabi %define gcc_icecream 1
add_cross cross-armv7hl-gcc$base_ver armv7hl armv7hl-tizen-linux-gnueabi %define gcc_icecream 1
else
add_cross cross-aarch64-gcc$base_ver aarch64 aarch64-tizen-linux
add_cross cross-armv7l-gcc$base_ver armv7l armv7l-tizen-linux-gnueabi
add_cross cross-armv7hl-gcc$base_ver armv7hl armv7hl-tizen-linux-gnueabi
fi

for f in *.spec; do
  sed -i -e '/^# .*-\(BEGIN\|END\)$/d' $f
done

exit 0
